### ISSUE TITLE
[Bug]: Invalid option(s) “queue_name” passed to the Redis Messenger transport

### ISSUE THREAD

**Issue by matthiashamacher** [pimcore/data-importer#226]
### Expected behavior

Redis Messenger should be supported

### Actual behavior

Redis Messenger is not supported as the configuration cannot be correctly changed

### Steps to reproduce

Set the transport configuration for the data importer to redis
```
framework:
    messenger:
        transports:
            pimcore_data_import: '%env(resolve:REDIS_MESSENGER_DSN)%/data-import'
```
The same issue was present in the pimcore core and was fixed with this issue: https://github.com/pimcore/pimcore/issues/11355
